[2025-10-10T14:31:57.814+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_spark_connection.test_spark manual__2025-10-10T14:31:48.993477+00:00 [queued]>
[2025-10-10T14:31:57.832+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_spark_connection.test_spark manual__2025-10-10T14:31:48.993477+00:00 [queued]>
[2025-10-10T14:31:57.833+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-10T14:31:57.865+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): test_spark> on 2025-10-10 14:31:48.993477+00:00
[2025-10-10T14:31:57.920+0000] {standard_task_runner.py:60} INFO - Started process 153 to run task
[2025-10-10T14:31:57.928+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_spark_connection', 'test_spark', 'manual__2025-10-10T14:31:48.993477+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmp2km93i39']
[2025-10-10T14:31:57.931+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask test_spark
[2025-10-10T14:31:58.106+0000] {task_command.py:423} INFO - Running <TaskInstance: test_spark_connection.test_spark manual__2025-10-10T14:31:48.993477+00:00 [running]> on host 9d2bfb6b2c68
[2025-10-10T14:31:58.736+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_spark_connection' AIRFLOW_CTX_TASK_ID='test_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-10-10T14:31:48.993477+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-10T14:31:48.993477+00:00'
[2025-10-10T14:31:58.894+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2025-10-10T14:31:58.898+0000] {spark_submit.py:341} INFO - Spark-Submit cmd: spark-submit --master spark://host.docker.internal:7077 --name arrow-spark --verbose /opt/***/dags/pi.py
[2025-10-10T14:31:59.230+0000] {spark_submit.py:492} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-10-10T14:31:59.293+0000] {spark_submit.py:492} INFO - JAVA_HOME is not set
[2025-10-10T14:31:59.447+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 423, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://host.docker.internal:7077 --name arrow-spark --verbose /opt/***/dags/pi.py. Error code is: 1.
[2025-10-10T14:31:59.577+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_spark_connection, task_id=test_spark, execution_date=20251010T143148, start_date=20251010T143157, end_date=20251010T143159
[2025-10-10T14:31:59.645+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task test_spark (Cannot execute: spark-submit --master spark://host.docker.internal:7077 --name arrow-spark --verbose /opt/***/dags/pi.py. Error code is: 1.; 153)
[2025-10-10T14:31:59.732+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-10T14:31:59.818+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
