[2025-10-30T14:56:12.180+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-30T14:16:13.943140+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-10-30T14:56:12.269+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-10-31T02:10:45.930+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-30T14:16:13.943140+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-10-31T02:10:47.196+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
